name: Test01
api: 4.0.0
version: 0.0.3
main: CHL\test\test
author: FRashkar-pm
commands:
  coba:
    description: "Coba untuk mencoba"
    usage: /coba
    permission: coba.use
    aliases: cba
permissions:
  coba.use:
    default: true
