name: Test01
api: 4.0.0
version: 0.0.1
main: Test01\Main
author: FRashkar-pm
commands:
  tests:
    description: "Test01"
    usage: /tests
    permission: tests.use
    aliases: tst
permissions:
  tests.use:
    default: true
